name = "QuantumJulia"
uuid = "fb60ebe1-2505-4b3f-b47e-dfb05b43f27b"
authors = ["JanSuntajs"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DrWatson = "2.18.0"
julia = "1.9.4"
